### PR TITLE
Friendshipsv1 feature

### PR DESCRIPTION
**Pull request by Zappat0n**
Changes included:
- Creation of friendship model
- Addition friendship model into the user model
- Creation of methods inside user model to access friends
- Changed user views to be able to see friendships
- Addition of methods to send an invitation to a user to become a friend
- Addition of methods to accept a friend request
- Addition of model and feature tests

### CODE REVIEW

**Review by ElijahTobs — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

## Hi @Zappat0n and @Nkuria  :wave: 

You've done well so far :+1:  and I commend you for that :clap: 
However, there are still some changes to be made before this milestone can be approved.

## REQUIRED

* [x] User can invite friends
- [x] User can see friendships requests
- [x] User has to accept friendship request to start friendship

- [x] User can reject a friendship request
- [x] There is a button to invite user to friendship on users list page and on single user page

- [x] Posts timeline includes posts written by logged-in user and their friends

### Make the requested changes and submit for another review. 
## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

**Review by arslanbisharat — CHANGES_REQUESTED** [review]
# Request changes 😳

I am very happy to see this project and I can see you worked hard on this project. There are only a few issues that we need to address and I am sure that you will end up with a perfect project

_It's okay. We are here to learn. Don't get discouraged. Work even harder. You are almost there.😄_

This is a great opportunity to learn. Microverse is here to help you. 

**Please have a look at the suggestions to get more understanding.**
- [ ] Please make changes requested by previous TSE and then request for code review



**Please make the changes and request a re-review for the given project**

If you get stuck somewhere, don't hesitate to reach me out or schedule s 1:1 meeting with a Full-time TSE. 

Stay safe and give me a smile 😇

### Happy Coding
---------------------------------------------------------------------------------------------------------------------------------
**Regards,
Arslan Bisharat
slack: arslanbisharat**

**Review by cristianCeamatu — CHANGES_REQUESTED** [review]
## ♻️ Changes required
#### Please stop submitting the project for review until you apply the mandatory requested changes. You just need to follow the tutorial provided by Microverse.

- [x] User can see friendships requests

- [x] User has to accept friendship request to start a friendship

- [x] User can reject a friendship request

- [x] There is a button to invite the user to friendship on the user's list page and on the single-user page

- [x] Posts timeline includes posts written by logged-in user and their friends

Don't hesitate to contact me on Slack if needed.

Best regards,
Cristian Ceamatu
Slack: Cristian Viorel Ceamatu

**Comment by Zappat0n** [comment]
I do not know what is happening but all these features are implemented since the first code review.

User can only invite friends that are not invited

invite_button

**Comment by Zappat0n** [comment]
User can accept or reject invites
accept_reject_invites

**Comment by Zappat0n** [comment]
Invitations can be accepted
accepted_invitation

**Comment by Zappat0n** [comment]
There is an option to invite a friend in the show page of the user
invite_from_show

**Comment by cristianCeamatu** [comment]
On my PC the `NVITE FRIEND` button appears all the time so I can request friendships multiple times, the accept reject button were so hidden that I saw them only after you showed the screens, please make them a different color or show them in some way. I am sure the previous reviewers had the same problems. Please re-check if the duplication friendship is still happening and ask for another review. Screenshots below:
Untitled1
Untitled3
Untitled

**Comment by Zappat0n** [comment]
> On my PC the `NVITE FRIEND` button appears all the time so I can request friendships multiple times, the accept reject button were so hidden that I saw them only after you showed the screens, please make them a different color or show them in some way. I am sure the previous reviewers had the same problems. Please re-check if the duplication friendship is still happening and ask for another review. Screenshots below:
> Untitled1
> Untitled3
> Untitled

Ok. Thank you very much for your reply. 
It is already fixed now. 
I am going to ask for another review.
Best regards.

**Comment by cristianCeamatu** [comment]
With pleasure guys! Good luck with your next projects!

**Review by MahmoudBakr23 — APPROVED** [review]
# **Approved ✔✔**

<hr>

Great job guys working on this milestone and all requested changes, it looks perfect to me now.
Good luck with next and happy coding 👨‍💻💻

**Pull request merged**
